[/Script/EngineSettings.GameMapsSettings]
; Любой уровень запускается с футбольным режимом — World Settings настраивать не нужно
GlobalDefaultGameMode=/Script/MiniFootball.SoccerGameMode

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=041DB14A4BE20B253136ACA94D8EF604
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=


[/Script/PythonScriptPlugin.PythonScriptPluginSettings]
bRemoteExecution=True
RemoteExecutionMulticastBindAddress=0.0.0.0
